# Generated by Django 2.2.4 on 2019-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methon', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=1000)),
            ],
        ),
    ]
